
spring:
  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    username: xudam
    password: xudam
    url: jdbc:mysql://118.25.70.78:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: cn.xudam.blog.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    root: info
    cn.xudam: debug
  file:
    max-history: 30
    path: log/blog-pro.log

server:
  port: 8081
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
